FROM node:20-alpine AS build
WORKDIR /app

ENV CI=true

COPY package.json package-lock.json ./
RUN npm install --no-audit --no-fund

COPY index.html ./
COPY tsconfig.json tsconfig.node.json ./
COPY vite.config.ts postcss.config.js tailwind.config.js ./
COPY postcss ./postcss
COPY src ./src
ARG VITE_API_BASE_URL=http://localhost:4000
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
RUN npm run build

FROM nginx:1.27-alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
