CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  theme TEXT NOT NULL DEFAULT 'cloud',
  timezone TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS habits (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  description TEXT,
  color TEXT NOT NULL,
  icon TEXT NOT NULL,
  frequency TEXT NOT NULL,
  "customDays" JSONB,
  schedule JSONB,
  "targetStreak" INTEGER NOT NULL,
  "dailyTarget" INTEGER NOT NULL DEFAULT 1,
  tags JSONB,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  "sortOrder" BIGINT NOT NULL DEFAULT 0,
  "reminderTime" TEXT,
  "reminderEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
  "lastReminderSentAt" TIMESTAMP,
  type TEXT NOT NULL DEFAULT 'positive',
  "freezeDays" JSONB DEFAULT '[]'::jsonb,
  "createdAt" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS checkins (
  id TEXT PRIMARY KEY,
  "habitId" TEXT NOT NULL REFERENCES habits(id),
  "userId" TEXT NOT NULL REFERENCES users(id),
  date DATE NOT NULL,
  done BOOLEAN NOT NULL,
  count INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT habit_date_unique UNIQUE("habitId", date)
);

CREATE TABLE IF NOT EXISTS tombstones (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id),
  entity TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  version INTEGER NOT NULL,
  "deletedAt" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_op_logs (
  "opId" TEXT PRIMARY KEY,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oauth_states (
  state TEXT PRIMARY KEY,
  "returnTo" TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id TEXT PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  "userId" TEXT NOT NULL REFERENCES users(id),
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expiresAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS push_subscriptions_userId_idx ON push_subscriptions("userId");
